# This is a basic workflow to help you get started with Actions

name: build-all-binaries

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: true

      # Runs a single command using the runners shell
      - name: Run model training, code generation and compilation
        uses: addnab/docker-run-action@v3
        with:
          image: registry.hub.docker.com/davidliyutong/sjtu-embsys:latest
          options: -v ${{ github.workspace }}:/opt/embsys/sjtu-embsys-2022
          run: |
            cd /opt/embsys/sjtu-embsys-2022
            bash ./ci/generate_code.sh
            bash ./ci/generate_code_stm32.sh
            bash ./ci/build_cmake.sh
            bash ./ci/build_stm32.sh
      
      - name: Run packing
        run: |
          bash ./ci/pack_output.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mnist_pythorch.tar.gz
          path: ./mnist_pythorch.tar.gz
